# -*- coding: utf-8 -*-
"""Fashion-MNIST(2124UDSF1006).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xCMKOeuc9ELPw7hLpScloobpcB4ajTNt
"""

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

(x_train, y_train), (x_test, y_test) = tf.keras.datasets.fashion_mnist.load_data()

x_train = x_train / 255.0
x_test = x_test / 255.0

x_train = x_train.reshape(-1,28,28,1)
x_test = x_test.reshape(-1,28,28,1)

model = Sequential([
    Conv2D(32, (3,3), activation='relu', input_shape=(28,28,1)),
    MaxPooling2D((2,2)),

    Conv2D(64, (3,3), activation='relu'),
    MaxPooling2D((2,2)),

    Flatten(),
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.fit(x_train, y_train, epochs=10, validation_data=(x_test, y_test))

loss, accuracy = model.evaluate(x_test, y_test)

print("Test Accuracy:", accuracy)

print("Test Loss:", loss)

import matplotlib.pyplot as plt
plt.imshow(x_train[0])

x_train.shape

x_test.shape

single_image=x_train[1]

single_image

single_image=x_train[0]

single_image

single_image.max()

single_image.min()

plt.imshow(single_image)

y_train

y_train.shape

y_test

y_test.shape

from tensorflow.keras.utils import to_categorical

y_cat_train=to_categorical(y_train)

y_cat_train[0]

y_cat_train.shape

y_cat_test=to_categorical(y_test,)

y_cat_test.shape

#data normalization
x_train=x_train/255
x_test=x_test/255

x_train[0].max()

x_train[0].min()

plt.imshow(x_train[0])

x_train=x_train.reshape(60000,28,28,1)

x_train.shape

x_test.shape

x_test=x_test.reshape(10000,28,28,1)

x_test

#building thw CNN Model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Conv2D,MaxPool2D,Flatten

model = Sequential()

model.add(Conv2D(filters=32, kernel_size=(4,4),input_shape=(28, 28, 1), activation='relu',))
model.add(MaxPool2D(pool_size=(2, 2)))

model.add(Flatten())

model.add(Dense(128, activation='relu'))

model.add(Dense(10, activation='softmax'))

model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

model.summary()

from tensorflow.keras.callbacks import EarlyStopping
early_stop = EarlyStopping(monitor='val_loss',patience=2)

model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

model.metrics_names

model.fit(x_train,y_cat_train,epochs=10,validation_data=(x_test,y_cat_test),callbacks=[early_stop])

